name: form_bloc
description: Easy Form State Management using BLoC pattern. Separate the Form State and Business Logic from the User Interface. Async Validation, Progress, Dynamic fields, and more.
version: 0.20.1
homepage: https://github.com/GiancarloCode/form_bloc/tree/master/packages/form_bloc
repository: https://github.com/GiancarloCode/form_bloc/tree/master/packages/form_bloc
issue_tracker: https://github.com/GiancarloCode/form_bloc/issues

environment:
  sdk: '>=2.6.0 <3.0.0'

dependencies:
  meta: ^1.3.0
  bloc: ^7.0.0-nullsafety.3
  bloc_test: ^8.0.0-nullsafety.2
  rxdart: ^0.26.0
  equatable: ^2.0.0
  quiver: ^3.0.0
  mockito: ^5.0.0
  pedantic: ^1.10.0
  collection: ^1.15.0
  uuid: ^3.0.1

dev_dependencies:
  test: ^1.16.0
